### ISSUE TITLE
Please improve information about access requirements.

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#10]
The readme states that a "test" key for CoBra is available but it is hard to see what is required if someone wants to deploy this into production - what charges/licences are involved etc. Will this require a commercial subscription?

This needs to be more clear in the readme, and also in the description within the plugins db.

**Comment by cellule-tice** [comment]
Hi Dan, I added some information as regards use of the plugin. Is it clearer now?

**Comment by jrm-unamur** [comment]
I added the following statement in both readme file and plugins db description:
"CoBRA text repository does not store or use any user data except for authentication data required to give access to priviledged users, that is users allowed to add or edit texts in the CoBRA repository."

Is that ok for you?

**Comment by danmarsden** [comment]
I was just thinking along the lines of how the plagiarism plugins handle user submitted content - although I'm not yet clear on what sort of content is actually stored by your system - perhaps it might make more sense when I get it running :-) - feel free to close this - the changes you've made seem to cover the basics!
