### ISSUE TITLE
Unhandled return type - {$a} during installation

### ISSUE THREAD

**Issue by fishfree** [cellule-tice/moodle-mod_cobra#14]
```
mod_cobra
Unhandled return type - {$a}

More information about this error

×Debug info: 
Error code: unhandledreturntype
×Stack trace:
line 494 of /lib/setuplib.php: moodle_exception thrown
line 93 of /mod/cobra/classes/cobra_remote_service.php: call to print_error()
line 454 of /mod/cobra/locallib.php: call to mod_cobra\cobra_remote_service::call()
line 37 of /mod/cobra/db/install.php: call to cobra_get_apikey()
line 784 of /lib/upgradelib.php: call to xmldb_cobra_install()
line 518 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()
```
After continueing, it goes to the CoBra setting page, after clicking "Request demo key", it shows: invalidrecord.
My Moodle version: 3.6

**Comment by jrm-unamur** [comment]
Hi,
You have encountered a problem during install that I cannot reproduce. I tested it again on a moodle 3.6 and install was successful.
I should have received a request from your moodle install on my cobra server but I didn't receive anything. Is your platform open to the web? or restricted to a local network?

**Comment by fishfree** [comment]
@jrm-unamur That's possible. I'm in China, you know, there is the notorious Great FIrewall. Can you tell me what's your Cobra server DNS or IP, or even any other destinations requested from my Moodle?

**Comment by jrm-unamur** [comment]
Hi!
The requested address is the one recorded in module config under serviceurl.
Good luck and keep me posted
Season's greetings

**Comment by fishfree** [comment]
After I enabling Debug mode, when I click "Request demo key" button, it shows error as below:

invalidrecord
File: /lib/dml/moodle_database.php
Line: 1546
Stack trace:
SELECT * FROM {external_functions} WHERE name = ?
[array (
  0 => 'mod_cobra_get_demo_api_key',
)]
Error code: invalidrecord
* line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 73 of /lib/externallib.php: call to moodle_database->get_record()
* line 185 of /lib/externallib.php: call to external_api::external_function_info()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by jrm-unamur** [comment]
Hi,
You must have had a problem during plugin install. I just checked again and you should have this line in {external_functions} table after install. Maybe you can try to uninstall the plugin and reinstall it.

**Comment by fishfree** [comment]
@jrm-unamur I tried both on a fresh Moodle 3.5 & 3.6, both failed with the same error.  My MySQL version is 5.7. BTW: I have the intention to cooperate with you to co-develop the corpus.

**Comment by jrm-unamur** [comment]
Hi,
Have you checked that webservice functions declarations are inserted in {external_functions} table?
I am sorry, but I installed it again on various configurations and I cannot reproduce this error. 
I will add some trace information on my cobra server to maybe collect information when your tries fail. Can you give me the following information: your site shortname, siteid, url and ip? (you can send that information by internal messenging on moodle.org platform).

**Comment by fishfree** [comment]
@jrm-unamur I sent you the private message in moodle.org. Thank you very much!
