### ISSUE TITLE
Please use internal Moodle curl class instead of PHP functions

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#2]
Some sites site behind a web proxy and the internal Moodle curl class takes care of this.

https://github.com/cellule-tice/moodle-mod_cobra/blob/494e62d4f76bb3444cdf239082e13e5377e96835/locallib.php#L105

**Comment by jrm-unamur** [comment]
fixed in commit https://github.com/cellule-tice/moodle-mod_cobra/commit/3a6ca82f067083f50d275f4d5b574564b1d1816d

**Comment by danmarsden** [comment]
Great! - you should also remove the function cobra_curl_request to avoid confusion when another dev reviews your code.
