### ISSUE TITLE
mysql specific function "group_concat"

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#3]
https://github.com/cellule-tice/moodle-mod_cobra/blob/494e62d4f76bb3444cdf239082e13e5377e96835/myglossary.php#L101

Moodle supports a number of different database types that do not support this function.

**Comment by jrm-unamur** [comment]
Fixed in commit https://github.com/cellule-tice/moodle-mod_cobra/commit/4d3be3bd9f9507296db3610b5022c8c3badb8cd4
