### ISSUE TITLE
custom css is not really specific enough and is not in standard styles.css file to help with caching.

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#6]
The cobra.css file contains a number of css changes that could conflict with other areas of Moodle code - the css is not specific enough.

they should all probably be prefixed with .path-mod-cobra - Once you have done this you could then move it into the normal "styles.css" file within the module and allow it to be cached a lot better.

**Comment by jrm-unamur** [comment]
Addressed in commit https://github.com/cellule-tice/moodle-mod_cobra/commit/46645bfa14ae28a477d62759f9d2d56eb7ef2ff1

**Comment by danmarsden** [comment]
nice! - you might want to close these when you've addresed them :-)
