### ISSUE TITLE
Please make it clear what "request Demo key" will do.

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#8]
I can see in the code that it will send the site supportemail, site shortname, the current user firstname and lastname to your external service, but that is not clear to the admin user when viewing the "settings.php" page.
It would be good if you could add some text under the button to say what information will be shared with you to obtain the demo key. I also wonder if Supportemail is the right one to use? - shouldn't it be the e-mail address of the admin user currently logged in?

**Comment by jrm-unamur** [comment]
issue #8 addressed in commit https://github.com/cellule-tice/moodle-mod_cobra/commit/54c8901857c9c65b6810c446ce312de7b9dbfbae

**Comment by danmarsden** [comment]
You need to improve that description to cover all the information you are sending - particularly the "user" related info (email addresses/names etc.)

**Comment by jrm-unamur** [comment]
I somewhat refactored what information is being sent when clicking "request demo key" button. We now only store information about the platform (shortname, ipaddress and url). I added "No user related information is sent to CoBRA remote server" at the end of the description

**Comment by danmarsden** [comment]
If I were you I would still be collecting the logged in users e-mail address at point of demo key request so you can contact someone in relation to the site. There's nothing wrong with the collection of the e-mail address, you just need to mention it's happening when doing the request - but totally up to you how you want to manage it!
