### ISSUE TITLE
error when trying to add cobra activity to a course.

### ISSUE THREAD

**Issue by danmarsden** [cellule-tice/moodle-mod_cobra#9]
see attached image.
![erroraddingcobra](https://user-images.githubusercontent.com/362798/48248459-4759ed00-e45c-11e8-9aaa-94fe53c5cb64.png)

**Comment by cellule-tice** [comment]
Hi Dan, 
Would you please try again (reinstall the plugin) with the "fixapprovalissues" branch?

Thanks in advance

**Comment by danmarsden** [comment]
now I'm seeing the error (using PHP 7.2 on my server - not sure if that is related though.)

Exception - Class 'cobra_remote_access_exception' not found
line 97 of /mod/cobra/classes/cobra_remote_service.php: Error thrown
line 139 of /mod/cobra/locallib.php: call to mod_cobra\cobra_remote_service::call()
line 253 of /mod/cobra/mod_form.php: call to cobra_get_collections_options_list()
line 961 of /lib/formslib.php: call to mod_cobra_mod_form->definition_after_data()
line 198 of /course/modedit.php: call to moodleform->display()

**Comment by jrm-unamur** [comment]
The error was raised because you didn't have a demo apikey recorded in plugin config. I've added a warning message in mod_edit form to inform that the key is mandatory in order to add cobra ressources.
Can you try once again?

**Comment by danmarsden** [comment]
yeah - after the update I was getting "Your platform is not allowed to access CoBRA service"

I was using an apikey that was generated when I first started testing this: 077afd8672b6d6b5dd6493ea5405171f21a4db60

I deleted that key, requested a new one and that error went away.

**Comment by jrm-unamur** [comment]
Nice!
